### PR TITLE
55-scsi-sg3_id.rules: removal of scsi_id, and cleanup

### PR DESCRIPTION
**Pull request by mwilck**
I've attempted a rewrite of systemd's 60-persistent-storage.rules, with the following goals:

 1) get rid of scsi_id, replace by sg calls / sysfs everywhere
    (this implies changes in 55-sg3-utils.rules)
 2) cleanly separate hardware detection, content detection (blkid), and
    symlink creation
 3) Improve general readability. For my taste, that means shorter
    lines, thus less conditions individual rules, thus more GOTOs
    separating blocks of code where certain conditins are known to
    hold.

This is the sg3_utils part. I also submitted a pull request for systemd:
https://github.com/systemd/systemd/pull/7594

### CODE REVIEW

**Comment by mwilck** [comment]
Hannes, it's been two weeks ... could you voice an opinion on this patch set? It would certainly be beneficial for the systemd pull request to have this one accepted first. If you disagree with my changes, could you give me directions what to modify?

**Comment by hreinecke** [comment]
Sigh. Github doesn't make for a nice patch-by-patch review.
(Or I'm too stupid to use it :-( )
Can you send me the patches individually by mail?
What I've seen so far some things need to be addressed:
- The 'compat' label should be moved to the patch actually using it
- The rules rewrite replaces tests like 'env{XXX}!="?*" with "env{XXX}=="0"', which is _not_ equivalent; the former tests if the variable is set, and the latter tests if the variable has the value '0'. I'd rather like to revisit that in detail to ensure nothing goes wrong here.

**Comment by mwilck** [comment]
Hannes, this is a github "feature", see [why are my commits in the wrong order?](https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/) and https://github.com/isaacs/github/issues/386.

If you look at the patches in the actual commit order
```
git log --oneline --reverse origin/master..
73c292d0c4ce 55-scsi-sg3_id.rules: fix SCSI_IDENT_LUN_NAA_EXT case
cf7f9f30b11a 55-scsi-sg3_id.rules: set WWN from SCSI_IDENT_LUN_NAA
89ee63d47ae3 55-scsi-sg3_id.rules: set serial for cciss devices
fb7a48413219 55-scsi-sg3_id.rules: compat rules in single block
b14166db8c13 55-scsi-sg3_id.rules: separate sysfs and sg inquiry code
e609491b559f 55-scsi-sg3_id.rules: type-independent node for inquiry
c57effb6c0b8 55-scsi-sg3_id.rules: support tape devices
```
"compat" is introduced in `fb7a48413219` and used only in the follow-up patches.

**Comment by mwilck** [comment]
Hannes, I've sent you the patches by e-mail. Ping for review...

**Comment by mwilck** [comment]
Updated the set of commits after Hannes' review. The current set has been tested for tapes too, using https://github.com/markh794/mhvtl.

**Pull request merged**
