### PR TITLE
Introduce Haiku support

### PR DESCRIPTION
**Pull request by alaviss**
This commit add [Haiku](https://www.haiku-os.org/) OS-specific implementation to `sg3_lib`

### CODE REVIEW

**Comment by doug-gilbert** [comment]
I have applied this patch to my upstream subversion repository and done enough extra so it will compile (on Haiku) with pre-release 1.47 . An example of how to use it on haiku would be _very_ useful! For example with a SATA SSD 'sg_inq /dev/disk/scsi/0/0/0/raw' fails badly. No better with a USB memory key.

**Comment by doug-gilbert** [comment]
In my subversion revision 905 mirrored at https://github.com/doug-gilbert/sg3_utils there is now Haiku support as suggested by the original post. I'm still unclear how to test it. This mirror should catch up in time.

**Comment by alaviss** [comment]
Sorry, I haven't touched Haiku for quite sometime so I'm not sure why is it not working.

As far as I know accessing the `raw` interface is the right way to do it, but it hadn't been tested much outside of `sg_get_config`: https://github.com/haikuports/haikuports/pull/2010#issuecomment-361621785.

**Comment by hreinecke** [comment]
Merged with git svn id 905.

**Pull request closed without merging**
